language: ruby
script: bundle exec rspec spec
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-19mode
  - jruby-18mode
  - ree
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-18mode
  fast_finish: true
notifications:
  email:
    recipients:
      - cbn@zbh.uni-hamburg.de
